version: "3.9"

services:
  db:
    image: postgres:16
    container_name: ms-smtp-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PG_DATABASE:-ms_smtp}
      POSTGRES_USER: ${PG_USER:-ms}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-ms}
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  ms_smtp:
    image: node:20-alpine
    container_name: ms-smtp-service
    working_dir: /app
    restart: unless-stopped
    command: sh -c "npm ci && npm run start"
    volumes:
      - ./:/app
    environment:
      PORT: ${PORT:-3000}
      API_TOKEN: ${API_TOKEN}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM_DEFAULT: ${SMTP_FROM_DEFAULT}
      SMTP_POOL: ${SMTP_POOL:-true}
      SMTP_MAX_CONNECTIONS: ${SMTP_MAX_CONNECTIONS:-5}
      SMTP_MAX_MESSAGES: ${SMTP_MAX_MESSAGES:-100}
      SMTP_TLS_REJECT_UNAUTH: ${SMTP_TLS_REJECT_UNAUTH:-true}
      LOG_DIR: ${LOG_DIR:-./data/logs}
      LOG_FILE_NAME: ${LOG_FILE_NAME:-email.log}
      TEMPLATES_DIR: ${TEMPLATES_DIR:-./data/templates}
      SWAGGER_PATH: ${SWAGGER_PATH:-/docs}
      DB_PROVIDER: ${DB_PROVIDER:-postgres}
      PG_HOST: ${PG_HOST:-db}
      PG_PORT: ${PG_PORT:-5432}
      PG_USER: ${PG_USER:-ms}
      PG_PASSWORD: ${PG_PASSWORD:-ms}
      PG_DATABASE: ${PG_DATABASE:-ms_smtp}
      PG_SSL: ${PG_SSL:-false}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
